/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rpl;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import java.awt.geom.*;
import javax.swing.border.*;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
        getContentPane().setBackground(Color.decode("0x312D22"));
        
        logoGr.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/logoGR.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaGr = new javax.swing.JLabel();
        hover = new RoundedPanel(50, new Color(249, 248, 242));
        homeButton = new javax.swing.JLabel();
        faqButton = new javax.swing.JLabel();
        masukButton = new javax.swing.JLabel();
        logoGr = new javax.swing.JLabel();
        keterangan = new javax.swing.JLabel();
        keterangan2 = new javax.swing.JLabel();
        namaGr2 = new javax.swing.JLabel();
        lowonganButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        namaGr.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        namaGr.setForeground(new java.awt.Color(249, 248, 242));
        namaGr.setText("Gendhu Roso");

        hover.setBackground(new java.awt.Color(49, 45, 34));

        homeButton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        homeButton.setForeground(new java.awt.Color(49, 45, 34));
        homeButton.setText("Home");
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout hoverLayout = new javax.swing.GroupLayout(hover);
        hover.setLayout(hoverLayout);
        hoverLayout.setHorizontalGroup(
            hoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoverLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        hoverLayout.setVerticalGroup(
            hoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        faqButton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        faqButton.setForeground(new java.awt.Color(249, 248, 242));
        faqButton.setText("FAQ");
        faqButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        masukButton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        masukButton.setForeground(new java.awt.Color(249, 248, 242));
        masukButton.setText("Masuk");
        masukButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        logoGr.setIcon(new javax.swing.ImageIcon("D:\\Semua Java Project\\RPL\\RPL\\RPL\\target\\classes\\com\\mycompany\\rpl\\resources\\logoGR.png")); // NOI18N

        keterangan.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        keterangan.setForeground(new java.awt.Color(249, 248, 242));
        keterangan.setText("RM Gendhu Roso merupakan warung makan prasmanan yang berlokasi di Kabupaten Wonosobo, Jawa Tengah. Dengan tema masakan Jawa,");

        keterangan2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        keterangan2.setForeground(new java.awt.Color(249, 248, 242));
        keterangan2.setText("Di sini menyediakan berbagai macam masakan rumahan, seperti sayuran dan lauk pauk serta minuman khas Jawa.");

        namaGr2.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        namaGr2.setForeground(new java.awt.Color(249, 248, 242));
        namaGr2.setText("Gendhu Roso");

        lowonganButton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lowonganButton.setForeground(new java.awt.Color(249, 248, 242));
        lowonganButton.setText("Lowongan");
        lowonganButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(namaGr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lowonganButton)
                .addGap(27, 27, 27)
                .addComponent(faqButton)
                .addGap(354, 354, 354)
                .addComponent(masukButton)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(360, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keterangan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(keterangan2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logoGr)
                            .addComponent(namaGr2))
                        .addGap(323, 323, 323)))
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masukButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lowonganButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaGr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(faqButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(101, 101, 101)
                .addComponent(logoGr)
                .addGap(18, 18, 18)
                .addComponent(namaGr2)
                .addGap(18, 18, 18)
                .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keterangan2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
                
            }
        });
        
        //custom codes for jform
        homepage home = new homepage();
        home.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        home.setResizable(false);   //No resize is possible
        home.setSize(1280, 720);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel faqButton;
    private javax.swing.JLabel homeButton;
    private javax.swing.JPanel hover;
    private javax.swing.JLabel keterangan;
    private javax.swing.JLabel keterangan2;
    private javax.swing.JLabel logoGr;
    private javax.swing.JLabel lowonganButton;
    private javax.swing.JLabel masukButton;
    private javax.swing.JLabel namaGr;
    private javax.swing.JLabel namaGr2;
    // End of variables declaration//GEN-END:variables

    
class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }
}
