/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rpl;

import java.awt.Color;
import java.awt.*;
import java.sql.SQLException;
import java.awt.geom.*;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.border.*;
import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ASUS
 */
public class hrd_loker extends javax.swing.JFrame {

    /**
     * Creates new form hrd_loker
     */
    public hrd_loker() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.decode("0xFFFFFF"));
        
        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/homeBlack.png")));
        pelamarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/pelamarBlack.png")));
        lokerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/lokersayaWhite.png")));
        pegawaiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/pegawaiBlack.png")));
        saranIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/saranBlack.png")));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/back2.png")));
        backButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/back2.png")));
        backButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/back2.png")));
    
        // remove border ngayeli di text area
        jScrollPane1.setBorder(null);
        jScrollPane2.setBorder(null);
        jScrollPane3.setBorder(null);
        jScrollPane4.setBorder(null);
        jScrollPane5.setBorder(null);
        jScrollPane6.setBorder(null);
        jScrollPane7.setBorder(null);
        jScrollPane8.setBorder(null);
        jScrollPane9.setBorder(null);
        ketjJM.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            ketjJMMouseClicked(evt);
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rincianLokerJM = new javax.swing.JDialog();
        judul1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel7 = new RoundedPanel(50, new Color(249, 248, 242));
        kualifikasiJM = new javax.swing.JLabel();
        tanggungJawabJM = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ketjJM = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        ketkualJM = new javax.swing.JTextArea();
        jPanel8 = new RoundedPanel(50, new Color(249, 248, 242));
        desJM = new javax.swing.JLabel();
        tenggat4 = new javax.swing.JLabel();
        keterangan21 = new javax.swing.JLabel();
        posisi1 = new javax.swing.JLabel();
        keterangan24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ketdesJM = new javax.swing.JTextArea();
        backButton = new javax.swing.JLabel();
        simpanJM = new javax.swing.JButton();
        rincianLokerP = new javax.swing.JDialog();
        judul2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel9 = new RoundedPanel(50, new Color(249, 248, 242));
        kualifikasiP = new javax.swing.JLabel();
        tanggungJawabP = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ketjP = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        ketkualP = new javax.swing.JTextArea();
        jPanel10 = new RoundedPanel(50, new Color(249, 248, 242));
        desP = new javax.swing.JLabel();
        tenggat5 = new javax.swing.JLabel();
        keterangan46 = new javax.swing.JLabel();
        posisi2 = new javax.swing.JLabel();
        keterangan22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ketdesP = new javax.swing.JTextArea();
        backButton1 = new javax.swing.JLabel();
        simpanP = new javax.swing.JButton();
        rincianLokerK = new javax.swing.JDialog();
        judul3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel11 = new RoundedPanel(50, new Color(249, 248, 242));
        kualifikasiK = new javax.swing.JLabel();
        tanggungJawabK = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        ketjK = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        ketkualK = new javax.swing.JTextArea();
        jPanel12 = new RoundedPanel(50, new Color(249, 248, 242));
        desK = new javax.swing.JLabel();
        tenggat6 = new javax.swing.JLabel();
        keterangan68 = new javax.swing.JLabel();
        posisi3 = new javax.swing.JLabel();
        keterangan25 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        ketdesK = new javax.swing.JTextArea();
        backButton2 = new javax.swing.JLabel();
        simpanK = new javax.swing.JButton();
        keterangan23 = new javax.swing.JLabel();
        nav = new RoundedPanel(100, new Color(215, 204, 185));
        pegawaiLabel = new javax.swing.JLabel();
        homeIcon = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        pelamarIcon = new javax.swing.JLabel();
        lokerIcon = new javax.swing.JLabel();
        pelamarLabel = new javax.swing.JLabel();
        pegawaiIcon = new javax.swing.JLabel();
        lokerLabel = new javax.swing.JLabel();
        saranIcon = new javax.swing.JLabel();
        saranLabel = new javax.swing.JLabel();
        jPanel1 = new RoundedPanel(70, new Color(49, 45, 34));
        logoutButton = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        copyright = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        support = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel(50, new Color(249, 248, 242));
        tenggatDISABLE = new javax.swing.JLabel();
        low4 = new javax.swing.JLabel();
        keterangan3 = new javax.swing.JLabel();
        rincianDISABLE = new javax.swing.JButton();
        jPanel3 = new RoundedPanel(50, new Color(249, 248, 242));
        tenggat1 = new javax.swing.JLabel();
        low1 = new javax.swing.JLabel();
        keterangan6 = new javax.swing.JLabel();
        editJM = new javax.swing.JButton();
        jPanel4 = new RoundedPanel(50, new Color(249, 248, 242));
        tenggat2 = new javax.swing.JLabel();
        low2 = new javax.swing.JLabel();
        keterangan9 = new javax.swing.JLabel();
        EditP = new javax.swing.JButton();
        jPanel5 = new RoundedPanel(50, new Color(249, 248, 242));
        tenggat3 = new javax.swing.JLabel();
        low3 = new javax.swing.JLabel();
        keterangan12 = new javax.swing.JLabel();
        EditK = new javax.swing.JButton();

        rincianLokerJM.setMinimumSize(new java.awt.Dimension(1100, 650));
        rincianLokerJM.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        judul1.setForeground(new java.awt.Color(112, 104, 94));
        judul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul1.setText("Daftar Lowongan Saya");
        rincianLokerJM.getContentPane().add(judul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 530, -1));

        jSeparator3.setForeground(new java.awt.Color(215, 204, 185));
        rincianLokerJM.getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 960, 20));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kualifikasiJM.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        kualifikasiJM.setForeground(new java.awt.Color(49, 45, 34));
        kualifikasiJM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kualifikasiJM.setText("Kualifikasi Pekerjaan");
        jPanel7.add(kualifikasiJM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 370, -1));

        tanggungJawabJM.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tanggungJawabJM.setForeground(new java.awt.Color(49, 45, 34));
        tanggungJawabJM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tanggungJawabJM.setText("Tanggung Jawab Utama");
        jPanel7.add(tanggungJawabJM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 370, -1));

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        ketjJM.setBackground(new java.awt.Color(249, 248, 242));
        ketjJM.setColumns(20);
        ketjJM.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ketjJM.setForeground(new java.awt.Color(49, 45, 34));
        ketjJM.setLineWrap(true);
        ketjJM.setRows(5);
        ketjJM.setText("1. Merencanakan dan menyiapkan item menu masakan\n2. Menyiapkan, memasak makanan sesuai pesanan dan mengikuti resep masakan\n3. Mengawasi operasional dapur, termasuk menjaga peralatan dapur tetap bersih\n4. Memantau kualitas dan presentasi makanan\n5. Mengelola persediaan dan bahan-bahan sesuai kebutuhan \n6. Mengawasi pengendalian porsi dan limbah untuk meminimalkan pemborosan\n7. Berkomunikasi dengan manajer untuk memperbaiki menu dan operasi dapur\n8. Mengembangkan resep baru sesuai permintaan pelanggan");
        ketjJM.setAutoscrolls(false);
        ketjJM.setBorder(null);
        ketjJM.setCaretColor(new java.awt.Color(249, 248, 242));
        ketjJM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ketjJM.setMaximumSize(new java.awt.Dimension(232, 84));
        ketjJM.setMinimumSize(new java.awt.Dimension(232, 84));
        ketjJM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ketjJMFocusLost(evt);
            }
        });
        ketjJM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ketjJMMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ketjJM);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 570, 190));

        ketkualJM.setBackground(new java.awt.Color(249, 248, 242));
        ketkualJM.setColumns(20);
        ketkualJM.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ketkualJM.setForeground(new java.awt.Color(49, 45, 34));
        ketkualJM.setLineWrap(true);
        ketkualJM.setRows(5);
        ketkualJM.setText("1. Laki-laki/ Perempuan\n2. Minimal usia 22 tahun\n3. Memiliki pengalaman di bidang memasak, minimal 2 tahun\n4. Menguasai dasar-dasar memasak (bahan, bumbu, dan proses memasak)\n5. Jujur, disiplin, dan bertanggung jawab\n6. Mempunyai skill leadership, teamwork, dan komunikasi yang baik");
        ketkualJM.setAutoscrolls(false);
        ketkualJM.setBorder(null);
        ketkualJM.setCaretColor(new java.awt.Color(249, 248, 242));
        ketkualJM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ketkualJM.setMaximumSize(new java.awt.Dimension(232, 84));
        ketkualJM.setMinimumSize(new java.awt.Dimension(232, 84));
        jScrollPane1.setViewportView(ketkualJM);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 570, 150));

        rincianLokerJM.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 640, 470));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desJM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        desJM.setForeground(new java.awt.Color(49, 45, 34));
        desJM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        desJM.setText("Deskripsi Pekerjaan");
        jPanel8.add(desJM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, 30));

        tenggat4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tenggat4.setForeground(new java.awt.Color(0, 74, 173));
        tenggat4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tenggat4.setText("12 Agustus 2024");
        jPanel8.add(tenggat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 20));

        keterangan21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        keterangan21.setForeground(new java.awt.Color(169, 42, 13));
        keterangan21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keterangan21.setText("*Klik untuk mengganti data kamu");
        jPanel8.add(keterangan21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, -1));

        posisi1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        posisi1.setForeground(new java.awt.Color(49, 45, 34));
        posisi1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        posisi1.setText("Juru Masak");
        jPanel8.add(posisi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 200, -1));

        keterangan24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        keterangan24.setForeground(new java.awt.Color(49, 45, 34));
        keterangan24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        keterangan24.setText("Berakhir pada:");
        jPanel8.add(keterangan24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, -1));

        ketdesJM.setBackground(new java.awt.Color(249, 248, 242));
        ketdesJM.setColumns(20);
        ketdesJM.setForeground(new java.awt.Color(49, 45, 34));
        ketdesJM.setLineWrap(true);
        ketdesJM.setRows(5);
        ketdesJM.setText("Sebagai juru masak, Anda akan bertanggung \njawab untuk menyiapkan dan memasak\nhidangan sesuai dengan standar rumah \nmakan kami. Anda akan bekerja sama dengan \ntim dapur untuk memastikan semua makanan \ndisajikan dengan rasa dan presentasi \nkonsisten");
        ketdesJM.setAutoscrolls(false);
        ketdesJM.setBorder(null);
        ketdesJM.setCaretColor(new java.awt.Color(249, 248, 242));
        ketdesJM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ketdesJM.setMaximumSize(new java.awt.Dimension(232, 84));
        ketdesJM.setMinimumSize(new java.awt.Dimension(232, 84));
        jScrollPane2.setViewportView(ketdesJM);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, 130));

        rincianLokerJM.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 290, 370));

        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        rincianLokerJM.getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, 160, 70));

        simpanJM.setBackground(new java.awt.Color(112, 104, 94));
        simpanJM.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        simpanJM.setForeground(new java.awt.Color(249, 248, 242));
        simpanJM.setText("Simpan");
        simpanJM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        simpanJM.setBorderPainted(false);
        simpanJM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanJM.setFocusable(false);
        simpanJM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanJMActionPerformed(evt);
            }
        });
        rincianLokerJM.getContentPane().add(simpanJM, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 190, 40));

        rincianLokerP.setMinimumSize(new java.awt.Dimension(1100, 650));
        rincianLokerP.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        judul2.setForeground(new java.awt.Color(112, 104, 94));
        judul2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul2.setText("Daftar Lowongan Saya");
        rincianLokerP.getContentPane().add(judul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 530, -1));

        jSeparator4.setForeground(new java.awt.Color(215, 204, 185));
        rincianLokerP.getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 960, 20));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kualifikasiP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        kualifikasiP.setForeground(new java.awt.Color(49, 45, 34));
        kualifikasiP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kualifikasiP.setText("Kualifikasi Pekerjaan");
        jPanel9.add(kualifikasiP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 370, -1));

        tanggungJawabP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tanggungJawabP.setForeground(new java.awt.Color(49, 45, 34));
        tanggungJawabP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tanggungJawabP.setText("Tanggung Jawab Utama");
        jPanel9.add(tanggungJawabP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 370, -1));

        ketjP.setBackground(new java.awt.Color(249, 248, 242));
        ketjP.setColumns(20);
        ketjP.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ketjP.setForeground(new java.awt.Color(49, 45, 34));
        ketjP.setLineWrap(true);
        ketjP.setRows(5);
        ketjP.setText("1. Mengambil pesanan secara akurat dan sampaikan ke staf dapur \n2. Menyajikan makanan dan minuman ke pelanggan secara tepat waktu dan efisien\n3. Menyapa dan melayani pelanggan dengan cara yang ramah dan profesional\n4. Mengelola dan menata meja agar tetap rapi dan bersih\n5. Memastikan kebutuhan tamu terpenuhi sepanjang waktu makan\n6. Menangani keluhan tamu dengan profesional dan segera mencari solusi\n7. Menjelaskan menu dan menjawab pertanyaan tentang hidangan dan minuman.\n8. Mengantar tamu ke meja yang tersedia dan memberikan menu");
        ketjP.setAutoscrolls(false);
        ketjP.setBorder(null);
        ketjP.setCaretColor(new java.awt.Color(249, 248, 242));
        ketjP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ketjP.setFocusable(false);
        ketjP.setMaximumSize(new java.awt.Dimension(232, 84));
        ketjP.setMinimumSize(new java.awt.Dimension(232, 84));
        ketjP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ketjPMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ketjP);

        jPanel9.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 570, 190));

        ketkualP.setBackground(new java.awt.Color(249, 248, 242));
        ketkualP.setColumns(20);
        ketkualP.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ketkualP.setForeground(new java.awt.Color(49, 45, 34));
        ketkualP.setLineWrap(true);
        ketkualP.setRows(5);
        ketkualP.setText("1. Laki-laki/ Perempuan\n2. Minimal usia 18 tahun\n3. Memiliki pengalaman sebagai pramusaji, minimal 1 tahun/tanpa pengalaman\n4. Memiliki kemampuan untuk beradaptasi dan bekerja secara efektif\n5. Jujur, disiplin, bertanggung jawab, dan berpenampilan yang rapi dan sopan\n6. Mempunyai skill leadership, teamwork, dan komunikasi yang baik");
        ketkualP.setAutoscrolls(false);
        ketkualP.setBorder(null);
        ketkualP.setCaretColor(new java.awt.Color(249, 248, 242));
        ketkualP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ketkualP.setFocusable(false);
        ketkualP.setMaximumSize(new java.awt.Dimension(232, 84));
        ketkualP.setMinimumSize(new java.awt.Dimension(232, 84));
        ketkualP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ketkualPMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(ketkualP);

        jPanel9.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 570, 150));

        rincianLokerP.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 640, 470));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        desP.setForeground(new java.awt.Color(49, 45, 34));
        desP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        desP.setText("Deskripsi Pekerjaan");
        jPanel10.add(desP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, 30));

        tenggat5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tenggat5.setForeground(new java.awt.Color(0, 74, 173));
        tenggat5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tenggat5.setText("12 Agustus 2024");
        jPanel10.add(tenggat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 20));

        keterangan46.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        keterangan46.setForeground(new java.awt.Color(49, 45, 34));
        keterangan46.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        keterangan46.setText("Berakhir pada:");
        jPanel10.add(keterangan46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, -1));

        posisi2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        posisi2.setForeground(new java.awt.Color(49, 45, 34));
        posisi2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        posisi2.setText("Pelayan");
        jPanel10.add(posisi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 200, -1));

        keterangan22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        keterangan22.setForeground(new java.awt.Color(169, 42, 13));
        keterangan22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keterangan22.setText("*Klik untuk mengganti data kamu");
        jPanel10.add(keterangan22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 20));

        ketdesP.setBackground(new java.awt.Color(249, 248, 242));
        ketdesP.setColumns(20);
        ketdesP.setForeground(new java.awt.Color(49, 45, 34));
        ketdesP.setLineWrap(true);
        ketdesP.setRows(5);
        ketdesP.setText("Sebagai pelayan/pramusaji, Anda akan \nbertanggung jawab untuk memberikan layanan \npelanggan dan memastikan setiap tamu untuk \nmemiliki pengalaman makan yang \nmenyenangkan");
        ketdesP.setAutoscrolls(false);
        ketdesP.setBorder(null);
        ketdesP.setCaretColor(new java.awt.Color(249, 248, 242));
        ketdesP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ketdesP.setFocusable(false);
        ketdesP.setMaximumSize(new java.awt.Dimension(232, 84));
        ketdesP.setMinimumSize(new java.awt.Dimension(232, 84));
        jScrollPane4.setViewportView(ketdesP);

        jPanel10.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 260, 130));

        rincianLokerP.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 290, 370));

        backButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButton1MouseClicked(evt);
            }
        });
        rincianLokerP.getContentPane().add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, 160, 70));

        simpanP.setBackground(new java.awt.Color(112, 104, 94));
        simpanP.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        simpanP.setForeground(new java.awt.Color(249, 248, 242));
        simpanP.setText("Simpan");
        simpanP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        simpanP.setBorderPainted(false);
        simpanP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanP.setFocusable(false);
        simpanP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPActionPerformed(evt);
            }
        });
        rincianLokerP.getContentPane().add(simpanP, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 190, 40));

        rincianLokerK.setMinimumSize(new java.awt.Dimension(1100, 650));
        rincianLokerK.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        judul3.setForeground(new java.awt.Color(112, 104, 94));
        judul3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul3.setText("Daftar Lowongan Saya");
        rincianLokerK.getContentPane().add(judul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 530, -1));

        jSeparator5.setForeground(new java.awt.Color(215, 204, 185));
        rincianLokerK.getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 960, 20));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kualifikasiK.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        kualifikasiK.setForeground(new java.awt.Color(49, 45, 34));
        kualifikasiK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kualifikasiK.setText("Kualifikasi Pekerjaan");
        jPanel11.add(kualifikasiK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 370, -1));

        tanggungJawabK.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tanggungJawabK.setForeground(new java.awt.Color(49, 45, 34));
        tanggungJawabK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tanggungJawabK.setText("Tanggung Jawab Utama");
        jPanel11.add(tanggungJawabK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 370, -1));

        ketjK.setBackground(new java.awt.Color(249, 248, 242));
        ketjK.setColumns(20);
        ketjK.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ketjK.setForeground(new java.awt.Color(49, 45, 34));
        ketjK.setLineWrap(true);
        ketjK.setRows(5);
        ketjK.setText("1. Mengambil pesanan secara akurat dan sampaikan ke staf dapur \n2. Menyajikan makanan minuman ke pelanggan secara tepat waktu dan efisien\n3. Menyapa dan melayani pelanggan dengan cara yang ramah dan profesional\n4. Mengelola dan menata meja agar tetap rapi dan bersih\n5. Memastikan kebutuhan tamu terpenuhi sepanjang waktu makan\n6. Menangani keluhan tamu dengan profesional dan segera mencari solusi\n7. Menjelaskan menu dan menjawab pertanyaan tentang hidangan dan minuman.\n8. Mengantar tamu ke meja yang tersedia dan memberikan menu");
        ketjK.setAutoscrolls(false);
        ketjK.setBorder(null);
        ketjK.setCaretColor(new java.awt.Color(249, 248, 242));
        ketjK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ketjK.setFocusable(false);
        ketjK.setMaximumSize(new java.awt.Dimension(232, 84));
        ketjK.setMinimumSize(new java.awt.Dimension(232, 84));
        jScrollPane7.setViewportView(ketjK);

        jPanel11.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 570, 190));

        ketkualK.setBackground(new java.awt.Color(249, 248, 242));
        ketkualK.setColumns(20);
        ketkualK.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ketkualK.setForeground(new java.awt.Color(49, 45, 34));
        ketkualK.setLineWrap(true);
        ketkualK.setRows(5);
        ketkualK.setText("1. Laki-laki/ Perempuan\n2. Minimal usia 18 tahun\n3. Memiliki pengalaman sebagai pramusaji, minimal 1 tahun/tanpa pengalaman\n4. Memiliki kemampuan untuk beradaptasi dan bekerja secara efektif\n5. Jujur, disiplin, bertanggung jawab, dan berpenampilan yang rapi dan sopan\n6. Mempunyai skill leadership, teamwork, dan komunikasi yang baik");
        ketkualK.setAutoscrolls(false);
        ketkualK.setBorder(null);
        ketkualK.setCaretColor(new java.awt.Color(249, 248, 242));
        ketkualK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ketkualK.setFocusable(false);
        ketkualK.setMaximumSize(new java.awt.Dimension(232, 84));
        ketkualK.setMinimumSize(new java.awt.Dimension(232, 84));
        jScrollPane8.setViewportView(ketkualK);

        jPanel11.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 570, 150));

        rincianLokerK.getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 640, 470));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        desK.setForeground(new java.awt.Color(49, 45, 34));
        desK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        desK.setText("Deskripsi Pekerjaan");
        jPanel12.add(desK, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, 30));

        tenggat6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tenggat6.setForeground(new java.awt.Color(0, 74, 173));
        tenggat6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tenggat6.setText("12 Agustus 2024");
        jPanel12.add(tenggat6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 20));

        keterangan68.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        keterangan68.setForeground(new java.awt.Color(49, 45, 34));
        keterangan68.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        keterangan68.setText("Berakhir pada:");
        jPanel12.add(keterangan68, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, -1));

        posisi3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        posisi3.setForeground(new java.awt.Color(49, 45, 34));
        posisi3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        posisi3.setText("Kasir");
        jPanel12.add(posisi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 200, 50));

        keterangan25.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        keterangan25.setForeground(new java.awt.Color(169, 42, 13));
        keterangan25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keterangan25.setText("*Klik untuk mengganti data kamu");
        jPanel12.add(keterangan25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 20));

        ketdesK.setBackground(new java.awt.Color(249, 248, 242));
        ketdesK.setColumns(20);
        ketdesK.setForeground(new java.awt.Color(49, 45, 34));
        ketdesK.setLineWrap(true);
        ketdesK.setRows(5);
        ketdesK.setText("Sebagai kasir, Anda akan bertanggung jawab \nuntuk menangani transaksi pembayaran \ndengan akurat dan efisien, serta memberikan \nlayanan kepada pelanggan dengan \nramah dan profesional");
        ketdesK.setAutoscrolls(false);
        ketdesK.setBorder(null);
        ketdesK.setCaretColor(new java.awt.Color(249, 248, 242));
        ketdesK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ketdesK.setFocusable(false);
        ketdesK.setMaximumSize(new java.awt.Dimension(232, 84));
        ketdesK.setMinimumSize(new java.awt.Dimension(232, 84));
        jScrollPane9.setViewportView(ketdesK);

        jPanel12.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 260, 130));

        rincianLokerK.getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 290, 370));

        backButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButton2MouseClicked(evt);
            }
        });
        rincianLokerK.getContentPane().add(backButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, 160, 70));

        simpanK.setBackground(new java.awt.Color(112, 104, 94));
        simpanK.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        simpanK.setForeground(new java.awt.Color(249, 248, 242));
        simpanK.setText("Simpan");
        simpanK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        simpanK.setBorderPainted(false);
        simpanK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanK.setFocusable(false);
        simpanK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKActionPerformed(evt);
            }
        });
        rincianLokerK.getContentPane().add(simpanK, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 190, 40));

        keterangan23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        keterangan23.setForeground(new java.awt.Color(49, 45, 34));
        keterangan23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        keterangan23.setText("Berakhir pada:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav.setBackground(new java.awt.Color(255, 255, 255));
        nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pegawaiLabel.setForeground(new java.awt.Color(49, 45, 34));
        pegawaiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pegawaiLabel.setText("Daftar Pegawai");
        nav.add(pegawaiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 90, 20));

        homeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeIconMouseClicked(evt);
            }
        });
        nav.add(homeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 60, 150, 50));

        homeLabel.setForeground(new java.awt.Color(49, 45, 34));
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel.setText("Home");
        nav.add(homeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 50, 30));

        pelamarIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pelamarIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pelamarIconMouseClicked(evt);
            }
        });
        nav.add(pelamarIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 170, 160, 70));

        lokerIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lokerIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lokerIconMouseClicked(evt);
            }
        });
        nav.add(lokerIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 280, 160, 60));

        pelamarLabel.setForeground(new java.awt.Color(49, 45, 34));
        pelamarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pelamarLabel.setText("Daftar Pelamar");
        nav.add(pelamarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 90, 20));

        pegawaiIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pegawaiIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pegawaiIconMouseClicked(evt);
            }
        });
        nav.add(pegawaiIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 390, 160, 60));

        lokerLabel.setForeground(new java.awt.Color(255, 255, 255));
        lokerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lokerLabel.setText("Loker Saya");
        nav.add(lokerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 90, 20));

        saranIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saranIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saranIconMouseClicked(evt);
            }
        });
        nav.add(saranIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 490, 160, 60));

        saranLabel.setForeground(new java.awt.Color(49, 45, 34));
        saranLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saranLabel.setText("Kotak Saran");
        nav.add(saranLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 90, 20));

        jPanel1.setBackground(new java.awt.Color(215, 204, 185));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        nav.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 90, 110));

        getContentPane().add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 620));

        logoutButton.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(49, 45, 34));
        logoutButton.setText("Logout");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, -1, -1));

        judul.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        judul.setForeground(new java.awt.Color(112, 104, 94));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        judul.setText("Daftar Lowongan Saya");
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 610, -1));

        jSeparator2.setForeground(new java.awt.Color(215, 204, 185));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 960, 20));

        copyright.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        copyright.setForeground(new java.awt.Color(49, 45, 34));
        copyright.setText("2024© Gendhu Roso");
        getContentPane().add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, -1, -1));

        about.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        about.setForeground(new java.awt.Color(49, 45, 34));
        about.setText("About     |");
        about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        getContentPane().add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 600, -1, -1));

        support.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        support.setForeground(new java.awt.Color(49, 45, 34));
        support.setText("Support");
        support.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        support.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supportMouseClicked(evt);
            }
        });
        getContentPane().add(support, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 600, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tenggatDISABLE.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenggatDISABLE.setForeground(new java.awt.Color(0, 74, 173));
        tenggatDISABLE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tenggatDISABLE.setText("-");
        jPanel2.add(tenggatDISABLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, 30));

        low4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        low4.setForeground(new java.awt.Color(49, 45, 34));
        low4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        low4.setText("Coming Soon");
        jPanel2.add(low4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 260, 50));

        keterangan3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        keterangan3.setForeground(new java.awt.Color(49, 45, 34));
        keterangan3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        keterangan3.setText("Berakhir pada:");
        jPanel2.add(keterangan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 30));

        rincianDISABLE.setBackground(new java.awt.Color(169, 161, 147));
        rincianDISABLE.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        rincianDISABLE.setForeground(new java.awt.Color(215, 204, 185));
        rincianDISABLE.setText("Edit");
        rincianDISABLE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rincianDISABLE.setBorderPainted(false);
        rincianDISABLE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rincianDISABLE.setFocusable(false);
        rincianDISABLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rincianDISABLEActionPerformed(evt);
            }
        });
        jPanel2.add(rincianDISABLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 190, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 430, 180));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tenggat1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenggat1.setForeground(new java.awt.Color(0, 74, 173));
        tenggat1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tenggat1.setText("12 Agustus 2024");
        jPanel3.add(tenggat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, 30));

        low1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        low1.setForeground(new java.awt.Color(49, 45, 34));
        low1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        low1.setText("Juru Masak");
        jPanel3.add(low1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, -1));

        keterangan6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        keterangan6.setForeground(new java.awt.Color(49, 45, 34));
        keterangan6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        keterangan6.setText("Berakhir pada:");
        jPanel3.add(keterangan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 30));

        editJM.setBackground(new java.awt.Color(112, 104, 94));
        editJM.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        editJM.setForeground(new java.awt.Color(249, 248, 242));
        editJM.setText("Edit");
        editJM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        editJM.setBorderPainted(false);
        editJM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editJM.setFocusable(false);
        editJM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJMActionPerformed(evt);
            }
        });
        jPanel3.add(editJM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 190, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 430, 180));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tenggat2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenggat2.setForeground(new java.awt.Color(0, 74, 173));
        tenggat2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tenggat2.setText("12 Agustus 2024");
        jPanel4.add(tenggat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, 30));

        low2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        low2.setForeground(new java.awt.Color(49, 45, 34));
        low2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        low2.setText("Pelayan");
        jPanel4.add(low2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 50));

        keterangan9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        keterangan9.setForeground(new java.awt.Color(49, 45, 34));
        keterangan9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        keterangan9.setText("Berakhir pada:");
        jPanel4.add(keterangan9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 30));

        EditP.setBackground(new java.awt.Color(112, 104, 94));
        EditP.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        EditP.setForeground(new java.awt.Color(249, 248, 242));
        EditP.setText("Edit");
        EditP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditP.setBorderPainted(false);
        EditP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditP.setFocusable(false);
        EditP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPActionPerformed(evt);
            }
        });
        jPanel4.add(EditP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 190, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 430, 180));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tenggat3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenggat3.setForeground(new java.awt.Color(0, 74, 173));
        tenggat3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tenggat3.setText("12 Agustus 2024");
        jPanel5.add(tenggat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, 30));

        low3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        low3.setForeground(new java.awt.Color(49, 45, 34));
        low3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        low3.setText("Kasir");
        jPanel5.add(low3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 50));

        keterangan12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        keterangan12.setForeground(new java.awt.Color(49, 45, 34));
        keterangan12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        keterangan12.setText("Berakhir pada:");
        jPanel5.add(keterangan12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 30));

        EditK.setBackground(new java.awt.Color(112, 104, 94));
        EditK.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        EditK.setForeground(new java.awt.Color(249, 248, 242));
        EditK.setText("Edit");
        EditK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditK.setBorderPainted(false);
        EditK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditK.setFocusable(false);
        EditK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditKActionPerformed(evt);
            }
        });
        jPanel5.add(EditK, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 190, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 430, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIconMouseClicked
        // TODO add your handling code here:
        dispose();
        try {
            new hrd_home().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(hrd_loker.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_homeIconMouseClicked

    private void pelamarIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pelamarIconMouseClicked
        // TODO add your handling code here:
        dispose();
        try {
            new hrd_pelamar().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(hrd_loker.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pelamarIconMouseClicked

    private void lokerIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lokerIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lokerIconMouseClicked

    private void pegawaiIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pegawaiIconMouseClicked
        // TODO add your handling code here:
        dispose();
        try {
            new hrd_pegawai().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(hrd_loker.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pegawaiIconMouseClicked

    private void saranIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saranIconMouseClicked
        // TODO add your handling code here:
        dispose();
        try {
            new hrd_saran().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(hrd_loker.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saranIconMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        dispose();
        new homepage().setVisible(true);
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMouseClicked

    private void supportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_supportMouseClicked

    private void rincianDISABLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rincianDISABLEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rincianDISABLEActionPerformed

    private void editJMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJMActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.readTextFromDatabase(ketjJM, ketkualJM, ketdesJM, tenggat4, posisi1);
        rincianLokerJM.setLocationRelativeTo(null);
        rincianLokerJM.setSize(1100, 650);
        rincianLokerJM.getContentPane().setBackground(Color.decode("0xFFFFFF"));
        rincianLokerJM.setVisible(true);
    }//GEN-LAST:event_editJMActionPerformed

    private void EditPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.readTextFromDatabase(ketjP, ketkualP, ketdesP, tenggat5, posisi2);
        rincianLokerP.setLocationRelativeTo(null);
        rincianLokerP.setSize(1100, 650);
        rincianLokerP.getContentPane().setBackground(Color.decode("0xFFFFFF"));
        rincianLokerP.setVisible(true);
    }//GEN-LAST:event_EditPActionPerformed

    private void EditKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditKActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.readTextFromDatabase(ketjK, ketkualK, ketdesK, tenggat6, posisi3);
        rincianLokerK.setLocationRelativeTo(null);
        rincianLokerK.setSize(1100, 650);
        rincianLokerK.getContentPane().setBackground(Color.decode("0xFFFFFF"));
        rincianLokerK.setVisible(true);
    }//GEN-LAST:event_EditKActionPerformed

    private void simpanJMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanJMActionPerformed
        // TODO add your handling code here:
        String newKetj = ketjJM.getText();
        String newKetkual = ketkualJM.getText();
        String newKetkdes = ketdesJM.getText();
        String posisi = posisi1.getText();
        String tanggal = tenggat4.getText();
        saveTextToDatabase(newKetj, newKetkual, newKetkdes, tanggal, posisi);
    }//GEN-LAST:event_simpanJMActionPerformed

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        rincianLokerJM.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void simpanPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPActionPerformed
        // TODO add your handling code here:
        String newKetj = ketjP.getText();
        String newKetkual = ketkualP.getText();
        String newKetkdes = ketdesP.getText();
        String posisi = posisi2.getText();
        String tanggal = tenggat5.getText();
        saveTextToDatabase(newKetj, newKetkual, newKetkdes, tanggal, posisi);
    }//GEN-LAST:event_simpanPActionPerformed

    private void backButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButton1MouseClicked
        // TODO add your handling code here:
        rincianLokerP.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_backButton1MouseClicked

    private void simpanKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanKActionPerformed
        // TODO add your handling code here:
        String newKetj = ketjK.getText();
        String newKetkual = ketkualK.getText();
        String newKetkdes = ketdesK.getText();
        String posisi = posisi3.getText();
        String tanggal = tenggat6.getText();
        saveTextToDatabase(newKetj, newKetkual, newKetkdes, tanggal, posisi);
    }//GEN-LAST:event_simpanKActionPerformed

    private void backButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButton2MouseClicked
        // TODO add your handling code here:
        rincianLokerK.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_backButton2MouseClicked

    private void ketjJMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ketjJMFocusLost
        // TODO add your handling code here:
        ketjJM.setEditable(false);
    }//GEN-LAST:event_ketjJMFocusLost

    private void ketjJMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ketjJMMouseClicked
        // TODO add your handling code here:
        ketjJM.setEditable(true);
    }//GEN-LAST:event_ketjJMMouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
        ketjJM.setEditable(true);
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void ketjPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ketjPMouseClicked
        // TODO add your handling code here:
        ketjP.setEditable(true);
    }//GEN-LAST:event_ketjPMouseClicked

    private void ketkualPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ketkualPMouseClicked
        // TODO add your handling code here:
        ketkualP.setEditable(true);
    }//GEN-LAST:event_ketkualPMouseClicked

    private void saveTextToDatabase(String newText1, String newText2, String newText3, String tanggal, String posisi) {
        Koneksi konek = new Koneksi();
        Connection koneksi = null;
        PreparedStatement statement = null;

        try {
            koneksi = konek.open();
            String query = "UPDATE loker SET text_1 = ?, text_2 = ?, text_3 = ?, tanggal = ? WHERE nama_loker = ?";
            statement = koneksi.prepareStatement(query);
            statement.setString(1, newText1);
            statement.setString(2, newText2);
            statement.setString(3, newText3);
            statement.setString(4, tanggal);
            statement.setString(5, posisi);

            int rowsUpdated = statement.executeUpdate();
            if (rowsUpdated > 0) {
                System.out.println("Perubahan berhasil disimpan.");
            } else {
                System.out.println("Gagal menyimpan perubahan.");
            }
        } catch (SQLException ex) {
            System.out.println("Kesalahan SQL terjadi: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            try {
                if (statement != null) {
                    statement.close();
                }
                if (koneksi != null && !koneksi.isClosed()) {
                    koneksi.close();
                }
            } catch (SQLException e) {
                System.out.println("Kesalahan saat menutup koneksi atau statement: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }
    
    private void readTextFromDatabase(JTextArea jTextArea1, JTextArea jTextArea2, JTextArea jTextArea3, JLabel JLabelTanggal, JLabel jLabelPosisi) {
        Koneksi konek = new Koneksi();
        Connection koneksi = null;
        PreparedStatement statement = null;
        ResultSet resultSet = null;

        try {
            koneksi = konek.open();
            String query = "SELECT text_1, text_2, text_3, tanggal, nama_loker FROM loker WHERE nama_loker = ?";
            statement = koneksi.prepareStatement(query);
            statement.setString(1, jLabelPosisi.getText());

            resultSet = statement.executeQuery();

            if (resultSet.next()) {
                jTextArea1.setText(resultSet.getString("text_1"));
                jTextArea2.setText(resultSet.getString("text_2"));
                jTextArea3.setText(resultSet.getString("text_3"));
                JLabelTanggal.setText(resultSet.getString("tanggal"));
                jLabelPosisi.setText(resultSet.getString("nama_loker"));
            } else {
                System.out.println("Data tidak ditemukan.");
            }
        } catch (SQLException ex) {
            System.out.println("Kesalahan SQL terjadi: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            try {
                if (resultSet != null) {
                    resultSet.close();
                }
                if (statement != null) {
                    statement.close();
                }
                if (koneksi != null && !koneksi.isClosed()) {
                    koneksi.close();
                }
            } catch (SQLException e) {
                System.out.println("Kesalahan saat menutup koneksi atau statement: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hrd_loker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hrd_loker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hrd_loker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hrd_loker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hrd_loker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditK;
    private javax.swing.JButton EditP;
    private javax.swing.JLabel about;
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel backButton1;
    private javax.swing.JLabel backButton2;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel desJM;
    private javax.swing.JLabel desK;
    private javax.swing.JLabel desP;
    private javax.swing.JButton editJM;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JTextArea ketdesJM;
    private javax.swing.JTextArea ketdesK;
    private javax.swing.JTextArea ketdesP;
    private javax.swing.JLabel keterangan12;
    private javax.swing.JLabel keterangan21;
    private javax.swing.JLabel keterangan22;
    private javax.swing.JLabel keterangan23;
    private javax.swing.JLabel keterangan24;
    private javax.swing.JLabel keterangan25;
    private javax.swing.JLabel keterangan3;
    private javax.swing.JLabel keterangan46;
    private javax.swing.JLabel keterangan6;
    private javax.swing.JLabel keterangan68;
    private javax.swing.JLabel keterangan9;
    private javax.swing.JTextArea ketjJM;
    private javax.swing.JTextArea ketjK;
    private javax.swing.JTextArea ketjP;
    private javax.swing.JTextArea ketkualJM;
    private javax.swing.JTextArea ketkualK;
    private javax.swing.JTextArea ketkualP;
    private javax.swing.JLabel kualifikasiJM;
    private javax.swing.JLabel kualifikasiK;
    private javax.swing.JLabel kualifikasiP;
    private javax.swing.JLabel logoutButton;
    private javax.swing.JLabel lokerIcon;
    private javax.swing.JLabel lokerLabel;
    private javax.swing.JLabel low1;
    private javax.swing.JLabel low2;
    private javax.swing.JLabel low3;
    private javax.swing.JLabel low4;
    private javax.swing.JPanel nav;
    private javax.swing.JLabel pegawaiIcon;
    private javax.swing.JLabel pegawaiLabel;
    private javax.swing.JLabel pelamarIcon;
    private javax.swing.JLabel pelamarLabel;
    private javax.swing.JLabel posisi1;
    private javax.swing.JLabel posisi2;
    private javax.swing.JLabel posisi3;
    private javax.swing.JButton rincianDISABLE;
    private javax.swing.JDialog rincianLokerJM;
    private javax.swing.JDialog rincianLokerK;
    private javax.swing.JDialog rincianLokerP;
    private javax.swing.JLabel saranIcon;
    private javax.swing.JLabel saranLabel;
    private javax.swing.JButton simpanJM;
    private javax.swing.JButton simpanK;
    private javax.swing.JButton simpanP;
    private javax.swing.JLabel support;
    private javax.swing.JLabel tanggungJawabJM;
    private javax.swing.JLabel tanggungJawabK;
    private javax.swing.JLabel tanggungJawabP;
    private javax.swing.JLabel tenggat1;
    private javax.swing.JLabel tenggat2;
    private javax.swing.JLabel tenggat3;
    private javax.swing.JLabel tenggat4;
    private javax.swing.JLabel tenggat5;
    private javax.swing.JLabel tenggat6;
    private javax.swing.JLabel tenggatDISABLE;
    // End of variables declaration//GEN-END:variables

class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
}

}
