/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rpl;

import java.awt.Color;
import java.awt.*;
import java.sql.SQLException;
import java.awt.geom.*;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.border.*;
import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JFrame;
        
/**
 *
 * @author ASUS
 */
public class lowonganpage extends javax.swing.JFrame {

    /**
     * Creates new form lowonganpage
     */
    public lowonganpage() {
        initComponents();
        getContentPane().setBackground(Color.decode("0x312D22"));
        
        jurumasakIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/juruMasak.png")));
        pelayanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/pelayan.png")));
        kasirIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/kasir.png")));
        saveIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/saveIcon.png")));
        saveIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/saveIcon.png")));
        saveIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/saveIcon.png")));
        shareIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/shareIcon.png")));
        shareIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/shareIcon.png")));
        shareIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("resources/shareIcon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeButton = new javax.swing.JLabel();
        namaGr = new javax.swing.JLabel();
        masukButton = new javax.swing.JLabel();
        lowonganButton = new javax.swing.JLabel();
        faqButton = new javax.swing.JLabel();
        hover = new RoundedPanel(50, new Color(249, 248, 242));
        jPanel1 = new RoundedPanel(50, new Color(249, 248, 242));
        kasirIcon = new javax.swing.JLabel();
        ket3 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        dl3 = new javax.swing.JLabel();
        rincianButton3 = new javax.swing.JButton();
        saveIcon3 = new javax.swing.JLabel();
        shareIcon3 = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel(50, new Color(249, 248, 242));
        jurumasakIcon = new javax.swing.JLabel();
        dl1 = new javax.swing.JLabel();
        rincianButton1 = new javax.swing.JButton();
        ket1 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        saveIcon1 = new javax.swing.JLabel();
        shareIcon1 = new javax.swing.JLabel();
        jPanel3 = new RoundedPanel(50, new Color(249, 248, 242));
        pelayanIcon = new javax.swing.JLabel();
        ket2 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        dl2 = new javax.swing.JLabel();
        rincianButton2 = new javax.swing.JButton();
        shareIcon2 = new javax.swing.JLabel();
        saveIcon2 = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        deskripsi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        homeButton.setForeground(new java.awt.Color(249, 248, 242));
        homeButton.setText("Home");
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, 50));

        namaGr.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        namaGr.setForeground(new java.awt.Color(249, 248, 242));
        namaGr.setText("Gendhu Roso");
        getContentPane().add(namaGr, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, 50));

        masukButton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        masukButton.setForeground(new java.awt.Color(249, 248, 242));
        masukButton.setText("Masuk");
        masukButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masukButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masukButtonMouseClicked(evt);
            }
        });
        getContentPane().add(masukButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, -1, 60));

        lowonganButton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lowonganButton.setForeground(new java.awt.Color(49, 45, 34));
        lowonganButton.setText("Lowongan");
        lowonganButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lowonganButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lowonganButtonMouseClicked(evt);
            }
        });
        getContentPane().add(lowonganButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 10, 140, 50));

        faqButton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        faqButton.setForeground(new java.awt.Color(249, 248, 242));
        faqButton.setText("FAQ");
        faqButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        faqButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faqButtonMouseClicked(evt);
            }
        });
        getContentPane().add(faqButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, 50));

        hover.setBackground(new java.awt.Color(49, 45, 34));
        hover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 170, 50));

        jPanel1.setBackground(new java.awt.Color(49, 45, 34));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kasirIcon.setIcon(new javax.swing.ImageIcon("D:\\Semua Java Project\\RPL\\RPL\\RPL\\target\\classes\\com\\mycompany\\rpl\\resources\\kasir.png")); // NOI18N
        jPanel1.add(kasirIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 30, 200, 110));

        ket3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        ket3.setForeground(new java.awt.Color(49, 45, 34));
        ket3.setText("Kasir");
        jPanel1.add(ket3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        label3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label3.setForeground(new java.awt.Color(49, 45, 34));
        label3.setText("Berakhir pada:");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, -1));

        dl3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        dl3.setForeground(new java.awt.Color(0, 74, 173));
        dl3.setText("12 Agustus 2024");
        jPanel1.add(dl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 130, -1));

        rincianButton3.setBackground(new java.awt.Color(112, 104, 94));
        rincianButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        rincianButton3.setForeground(new java.awt.Color(249, 248, 242));
        rincianButton3.setText("Rincian");
        rincianButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rincianButton3.setBorderPainted(false);
        rincianButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rincianButton3.setFocusable(false);
        rincianButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rincianButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(rincianButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 150, 40));

        saveIcon3.setIcon(new javax.swing.ImageIcon("D:\\Semua Java Project\\RPL\\RPL\\RPL\\target\\classes\\com\\mycompany\\rpl\\resources\\saveIcon.png")); // NOI18N
        jPanel1.add(saveIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, 40));

        shareIcon3.setIcon(new javax.swing.ImageIcon("D:\\Semua Java Project\\RPL\\RPL\\RPL\\target\\classes\\com\\mycompany\\rpl\\resources\\shareIcon.png")); // NOI18N
        jPanel1.add(shareIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 330, 300));

        jPanel2.setBackground(new java.awt.Color(49, 45, 34));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jurumasakIcon.setIcon(new javax.swing.ImageIcon("D:\\Semua Java Project\\RPL\\RPL\\RPL\\target\\classes\\com\\mycompany\\rpl\\resources\\juruMasak.png")); // NOI18N
        jPanel2.add(jurumasakIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 30, 200, 110));

        dl1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        dl1.setForeground(new java.awt.Color(0, 74, 173));
        dl1.setText("12 Agustus 2024");
        jPanel2.add(dl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 130, -1));

        rincianButton1.setBackground(new java.awt.Color(112, 104, 94));
        rincianButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        rincianButton1.setForeground(new java.awt.Color(249, 248, 242));
        rincianButton1.setText("Rincian");
        rincianButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rincianButton1.setBorderPainted(false);
        rincianButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rincianButton1.setFocusable(false);
        rincianButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rincianButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(rincianButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 150, 40));

        ket1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        ket1.setForeground(new java.awt.Color(49, 45, 34));
        ket1.setText("Juru Masak");
        jPanel2.add(ket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        label1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label1.setForeground(new java.awt.Color(49, 45, 34));
        label1.setText("Berakhir pada:");
        jPanel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, -1));

        saveIcon1.setIcon(new javax.swing.ImageIcon("D:\\Semua Java Project\\RPL\\RPL\\RPL\\target\\classes\\com\\mycompany\\rpl\\resources\\saveIcon.png")); // NOI18N
        jPanel2.add(saveIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, 40));

        shareIcon1.setIcon(new javax.swing.ImageIcon("D:\\Semua Java Project\\RPL\\RPL\\RPL\\target\\classes\\com\\mycompany\\rpl\\resources\\shareIcon.png")); // NOI18N
        jPanel2.add(shareIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 330, 300));

        jPanel3.setBackground(new java.awt.Color(49, 45, 34));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pelayanIcon.setIcon(new javax.swing.ImageIcon("D:\\Semua Java Project\\RPL\\RPL\\RPL\\target\\classes\\com\\mycompany\\rpl\\resources\\pelayan.png")); // NOI18N
        jPanel3.add(pelayanIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 30, 200, 110));

        ket2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        ket2.setForeground(new java.awt.Color(49, 45, 34));
        ket2.setText("Pelayan");
        jPanel3.add(ket2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        label2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label2.setForeground(new java.awt.Color(49, 45, 34));
        label2.setText("Berakhir pada:");
        jPanel3.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, -1));

        dl2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        dl2.setForeground(new java.awt.Color(0, 74, 173));
        dl2.setText("12 Agustus 2024");
        jPanel3.add(dl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 130, -1));

        rincianButton2.setBackground(new java.awt.Color(112, 104, 94));
        rincianButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        rincianButton2.setForeground(new java.awt.Color(249, 248, 242));
        rincianButton2.setText("Rincian");
        rincianButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rincianButton2.setBorderPainted(false);
        rincianButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rincianButton2.setFocusable(false);
        rincianButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rincianButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(rincianButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 150, 40));

        shareIcon2.setIcon(new javax.swing.ImageIcon("D:\\Semua Java Project\\RPL\\RPL\\RPL\\target\\classes\\com\\mycompany\\rpl\\resources\\shareIcon.png")); // NOI18N
        jPanel3.add(shareIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 140, 40));

        saveIcon2.setIcon(new javax.swing.ImageIcon("D:\\Semua Java Project\\RPL\\RPL\\RPL\\target\\classes\\com\\mycompany\\rpl\\resources\\saveIcon.png")); // NOI18N
        jPanel3.add(saveIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 140, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 350, 300));

        judul.setFont(new java.awt.Font("Segoe UI Black", 1, 40)); // NOI18N
        judul.setForeground(new java.awt.Color(249, 248, 242));
        judul.setText("Lowongan yang Tersedia");
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        deskripsi.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        deskripsi.setForeground(new java.awt.Color(249, 248, 242));
        deskripsi.setText("Lowongan yang tersedia ini mungkin cocok sama kamu. Ayo lihat!");
        getContentPane().add(deskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 550, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        // TODO add your handling code here:
        dispose();
        new homepage().setVisible(true);
    }//GEN-LAST:event_homeButtonMouseClicked

    private void lowonganButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lowonganButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lowonganButtonMouseClicked

    private void faqButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faqButtonMouseClicked
        // TODO add your handling code here:
        dispose();
        new faqpage().setVisible(true);
    }//GEN-LAST:event_faqButtonMouseClicked

    private void masukButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masukButtonMouseClicked
        // TODO add your handling code here:
        dispose();
        new loginpage().setVisible(true);
    }//GEN-LAST:event_masukButtonMouseClicked

    private void rincianButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rincianButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rincianButton3ActionPerformed

    private void rincianButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rincianButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rincianButton2ActionPerformed

    private void rincianButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rincianButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rincianButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lowonganpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lowonganpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lowonganpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lowonganpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lowonganpage().setVisible(true);
            }
        });
        
        lowonganpage lowongan = new lowonganpage();
        lowongan.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        lowongan.setResizable(false);   //No resize is possible
        lowongan.setSize(1280, 720);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deskripsi;
    private javax.swing.JLabel dl1;
    private javax.swing.JLabel dl2;
    private javax.swing.JLabel dl3;
    private javax.swing.JLabel faqButton;
    private javax.swing.JLabel homeButton;
    private javax.swing.JPanel hover;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel jurumasakIcon;
    private javax.swing.JLabel kasirIcon;
    private javax.swing.JLabel ket1;
    private javax.swing.JLabel ket2;
    private javax.swing.JLabel ket3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel lowonganButton;
    private javax.swing.JLabel masukButton;
    private javax.swing.JLabel namaGr;
    private javax.swing.JLabel pelayanIcon;
    private javax.swing.JButton rincianButton1;
    private javax.swing.JButton rincianButton2;
    private javax.swing.JButton rincianButton3;
    private javax.swing.JLabel saveIcon1;
    private javax.swing.JLabel saveIcon2;
    private javax.swing.JLabel saveIcon3;
    private javax.swing.JLabel shareIcon1;
    private javax.swing.JLabel shareIcon2;
    private javax.swing.JLabel shareIcon3;
    // End of variables declaration//GEN-END:variables

class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }

private static class RoundedBorder implements Border {

    private int radius;


    RoundedBorder(int radius) {
        this.radius = radius;
    }


    public Insets getBorderInsets(Component c) {
        return new Insets(this.radius+1, this.radius+1, this.radius+2, this.radius);
    }


    public boolean isBorderOpaque() {
        return true;
    }


    public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
        g.drawRoundRect(x, y, width-1, height-1, radius, radius);
    }
}

}
